POST http://localhost:5050/auth/login
content-type: application/json

{
    "email": "verstappen@redbull.at",
    "password": "secret"
}

###

GET http://localhost:5050/auth/logout

###

GET http://localhost:5050/auth/loggedin